dist: xenial

language: go

go:
  - 1.11.x
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

before_script:
  - go get -u golang.org/x/lint/golint

script:
  - golint ./...
  - go vet ./...
  - go test -v -race ./...
